# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-12 21:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expose',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf', models.FileField(upload_to='', verbose_name='Bild')),
            ],
            options={
                'verbose_name_plural': 'Exposés',
                'ordering': ('realestate',),
                'verbose_name': 'Exposé',
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='', verbose_name='Bild')),
                ('short_description', models.CharField(help_text='Die Kurzbeschreibung erscheint als Titel im Bild.', max_length=255, verbose_name='Kurzbeschreibung/Schlagwort')),
                ('long_description', models.TextField(blank=True, help_text='Die längere Beschreibung erscheint im Bild unter der Kurzbeschreibung. Keinen zu langen Text verwenden.', verbose_name='Längere Beschreibung')),
            ],
            options={
                'verbose_name_plural': 'Bilder',
                'ordering': ('realestate',),
                'verbose_name': 'Bild',
            },
        ),
        migrations.CreateModel(
            name='RealEstate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('online', models.BooleanField(default=True, help_text='Dieses Feld kann benutzt werden, um eine Wohnung erst später freizuschalten.', verbose_name='Online')),
                ('title', models.CharField(max_length=255, verbose_name='Titel')),
                ('rooms', models.PositiveIntegerField(default=4, verbose_name='Zimmer')),
                ('size', models.PositiveIntegerField(help_text='Angabe in m²', verbose_name='Größe')),
                ('floor', models.CharField(blank=True, max_length=255, verbose_name='Etage')),
                ('balcony', models.BooleanField(verbose_name='Balkon/Terrasse')),
                ('elevator', models.BooleanField(verbose_name='Aufzug')),
                ('netto', models.FloatField(help_text='Angabe in Euro.', verbose_name='Kaltmiete')),
                ('extra_costs', models.FloatField(help_text='Angabe in Euro. Die Position enthält auch die Heizkosten. Der Heizkostenanteil kann in der Beschreibung erwähnt werden.', verbose_name='Betriebskosten')),
                ('deposit', models.CharField(default='Nach Vereinbarung', max_length=255, verbose_name='Kaution')),
                ('description', models.TextField(help_text='Absätze sind durch Leerzeilen zu trennen. Die ersten 20 Wörter sind der Anrisstext auf der Startseite. Dieser ist in nur einem Absatz formatiert.', verbose_name='Beschreibung')),
            ],
            options={
                'verbose_name_plural': 'Wohnungen/Grundstücke',
                'verbose_name': 'Wohnung/Grundstück',
            },
        ),
        migrations.AddField(
            model_name='image',
            name='realestate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='THHome.RealEstate', verbose_name='Wohnung/Grundstück'),
        ),
        migrations.AddField(
            model_name='expose',
            name='realestate',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='THHome.RealEstate', verbose_name='Wohnung/Grundstück'),
        ),
    ]
