# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-29 22:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Titel')),
                ('text', models.TextField(verbose_name='Text')),
                ('icon', models.CharField(default='star', help_text='Siehe http://fontawesome.io/icons/.', max_length=255, verbose_name='Icon')),
                ('weight', models.IntegerField(default=100, help_text='Bestimmt die Reihenfolge der Elemente. Elemente mit größeren Zahlen erscheinen weiter unten beziehungsweise hinten.', verbose_name='Gewichtung')),
            ],
            options={
                'verbose_name': 'Sonderaktion',
                'ordering': ('weight',),
                'verbose_name_plural': 'Sonderaktionen',
            },
        ),
        migrations.CreateModel(
            name='Expose',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf', models.FileField(upload_to='', verbose_name='Exposé-Datei')),
            ],
            options={
                'verbose_name': 'Exposé',
                'ordering': ('realestate',),
                'verbose_name_plural': 'Exposés',
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='', verbose_name='Bild')),
                ('short_description', models.CharField(help_text='Die Kurzbeschreibung erscheint als Titel im Bild.', max_length=255, verbose_name='Kurzbeschreibung/Schlagwort')),
                ('long_description', models.TextField(blank=True, help_text='Die längere Beschreibung erscheint im Bild unter der Kurzbeschreibung. Keinen zu langen Text verwenden.', verbose_name='Längere Beschreibung')),
                ('weight', models.IntegerField(default=100, help_text='Bestimmt die Reihenfolge der Elemente. Elemente mit größeren Zahlen erscheinen weiter unten beziehungsweise hinten. Das erste Bild erscheint auf der Startseite.', verbose_name='Gewichtung')),
            ],
            options={
                'verbose_name': 'Bild für Wohnung/Grundstück',
                'ordering': ('realestate', 'weight'),
                'verbose_name_plural': 'Bilder für Wohnungen/Grundstücke',
            },
        ),
        migrations.CreateModel(
            name='Impression',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(help_text='Bildformat 650 x 350', upload_to='', verbose_name='Bild')),
                ('short_description', models.CharField(help_text='Die Kurzbeschreibung erscheint als Titel im Bild.', max_length=255, verbose_name='Kurzbeschreibung/Schlagwort')),
                ('long_description', models.TextField(blank=True, help_text='Die längere Beschreibung erscheint im Bild unter der Kurzbeschreibung. Keinen zu langen Text verwenden.', verbose_name='Längere Beschreibung')),
                ('weight', models.IntegerField(default=100, help_text='Bestimmt die Reihenfolge der Elemente. Elemente mit größeren Zahlen erscheinen weiter unten beziehungsweise hinten.', verbose_name='Gewichtung')),
            ],
            options={
                'verbose_name': 'Bild für Impression',
                'ordering': ('weight',),
                'verbose_name_plural': 'Bilder für Impressionen',
            },
        ),
        migrations.CreateModel(
            name='RealEstate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('online', models.BooleanField(default=True, help_text='Dieses Feld kann benutzt werden, um eine Wohnung erst später freizuschalten.', verbose_name='Online')),
                ('title', models.CharField(max_length=255, verbose_name='Titel')),
                ('description', models.TextField(help_text='Absätze sind durch Leerzeilen zu trennen. Die ersten 20 Wörter sind der Anrisstext auf der Startseite. Dieser ist in nur einem Absatz formatiert.', verbose_name='Beschreibung')),
                ('rooms', models.PositiveIntegerField(default=4, verbose_name='Zimmer')),
                ('size', models.PositiveIntegerField(help_text='Angabe in m²', verbose_name='Größe')),
                ('floor', models.CharField(blank=True, max_length=255, verbose_name='Etage')),
                ('balcony', models.BooleanField(verbose_name='Balkon/Terrasse')),
                ('elevator', models.BooleanField(verbose_name='Aufzug')),
                ('when_free', models.CharField(default='sofort', max_length=255, verbose_name='Verfügbar ab')),
                ('netto', models.FloatField(help_text='Angabe in Euro.', verbose_name='Kaltmiete')),
                ('extra_costs_cold', models.FloatField(help_text='Angabe in Euro.', verbose_name='Kalte Betriebskosten')),
                ('extra_costs_heating', models.FloatField(help_text='Angabe in Euro.', verbose_name='Heizkosten')),
                ('split_extra_costs', models.BooleanField(help_text='Ist dieses Feld aktiviert, werden kalte Betriebskosten und Heizkosten getrennt ausgewiesen. Ansonsten wird die Summe gebildet.', verbose_name='Getrennte Ausweisung der Betriebskosten')),
                ('deposit', models.CharField(default='Nach Vereinbarung', max_length=255, verbose_name='Kaution')),
                ('details', models.CharField(blank=True, help_text='Details mit Kommas trennen, zum Beispiel: Fußbodenheizung,Kamin,WG geeignet,Badewanne', max_length=255, verbose_name='Details')),
                ('energy_certificate', models.CharField(help_text='Angaben mit Kommas trennen, zum Beispiel: Verbrauchsausweis,100 kWH/(m²*a),Erdgas,1980,B', max_length=255, verbose_name='Energieausweis')),
            ],
            options={
                'verbose_name': 'Wohnung/Grundstück',
                'verbose_name_plural': 'Wohnungen/Grundstücke',
            },
        ),
        migrations.AddField(
            model_name='image',
            name='realestate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='THHome.RealEstate', verbose_name='Wohnung/Grundstück'),
        ),
        migrations.AddField(
            model_name='expose',
            name='realestate',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='THHome.RealEstate', verbose_name='Wohnung/Grundstück'),
        ),
    ]
