# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-06-08 20:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('THHome', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Titel')),
                ('text', models.TextField(verbose_name='Text')),
                ('icon', models.CharField(default='star', help_text='Siehe http://fontawesome.io/icons/.', max_length=255, verbose_name='Icon')),
                ('weight', models.IntegerField(default=100, help_text='Bestimmt die Reihenfolge der Elemente. Elemente mit größeren Zahlen erscheinen weiter unten beziehungsweise hinten.', verbose_name='Gewichtung')),
            ],
            options={
                'verbose_name_plural': 'Vorteile der Wohnanlage',
                'verbose_name': 'Vorteil der Wohnanlage',
                'ordering': ('weight',),
            },
        ),
    ]
