# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-06-10 20:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('THHome', '0002_about'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deal',
            old_name='text',
            new_name='short_text',
        ),
    ]
