# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-06-10 20:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('THHome', '0003_auto_20160610_2205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='short_text',
            field=models.TextField(help_text='Kurzer Anrisstext zur Bescheibung der Aktion.', verbose_name='Kurzer Text'),
        ),
    ]
