# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-06-10 20:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('THHome', '0004_auto_20160610_2205'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='details',
            field=models.TextField(default='Details', help_text='Längerer Text zur Bescheibung der Aktion, der erst nach Klick auf den Details-Button erscheint.', verbose_name='Details'),
            preserve_default=False,
        ),
    ]
