# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-10 20:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('THHome', '0005_deal_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='weight',
            field=models.IntegerField(default=100, help_text=b'Bestimmt die Reihenfolge der Elemente. Elemente mit gr\xc3\xb6\xc3\x9feren Zahlen erscheinen weiter unten beziehungsweise hinten.', verbose_name=b'Gewichtung'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='details',
            field=models.TextField(help_text=b'L\xc3\xa4ngerer Text zur Bescheibung der Aktion, der erst nach Klick auf den Details-Button erscheint. HTML-Tags sind m\xc3\xb6glich. Der Text wird jedoch automatisch in ein &lt;p&gt; Tag gesetzt.', verbose_name=b'Details'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='short_text',
            field=models.TextField(help_text=b'Kurzer Anrisstext zur Bescheibung der Aktion. HTML-Tags sind m\xc3\xb6glich. Der Text wird jedoch automatisch in ein &lt;p&gt; Tag gesetzt.', verbose_name=b'Kurzer Text'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='weight',
            field=models.IntegerField(default=100, help_text=b'Bestimmt die Reihenfolge der Elemente. Elemente mit gr\xc3\xb6\xc3\x9feren Zahlen erscheinen weiter unten beziehungsweise hinten.', verbose_name=b'Gewichtung'),
        ),
        migrations.AlterField(
            model_name='expose',
            name='pdf',
            field=models.FileField(upload_to=b'', verbose_name=b'Expos\xc3\xa9-Datei'),
        ),
        migrations.AlterField(
            model_name='expose',
            name='realestate',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='THHome.RealEstate', verbose_name=b'Wohnung/Grundst\xc3\xbcck'),
        ),
        migrations.AlterField(
            model_name='image',
            name='long_description',
            field=models.TextField(blank=True, help_text=b'Die l\xc3\xa4ngere Beschreibung erscheint im Bild unter der Kurzbeschreibung. Keinen zu langen Text verwenden.', verbose_name=b'L\xc3\xa4ngere Beschreibung'),
        ),
        migrations.AlterField(
            model_name='image',
            name='realestate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='THHome.RealEstate', verbose_name=b'Wohnung/Grundst\xc3\xbcck'),
        ),
        migrations.AlterField(
            model_name='image',
            name='weight',
            field=models.IntegerField(default=100, help_text=b'Bestimmt die Reihenfolge der Elemente. Elemente mit gr\xc3\xb6\xc3\x9feren Zahlen erscheinen weiter unten beziehungsweise hinten. Das erste Bild erscheint auf der Startseite.', verbose_name=b'Gewichtung'),
        ),
        migrations.AlterField(
            model_name='impression',
            name='image',
            field=models.FileField(help_text=b'Bildformat 650 x 487', upload_to=b'', verbose_name=b'Bild'),
        ),
        migrations.AlterField(
            model_name='impression',
            name='long_description',
            field=models.TextField(blank=True, help_text=b'Die l\xc3\xa4ngere Beschreibung erscheint im Bild unter der Kurzbeschreibung. Keinen zu langen Text verwenden.', verbose_name=b'L\xc3\xa4ngere Beschreibung'),
        ),
        migrations.AlterField(
            model_name='impression',
            name='weight',
            field=models.IntegerField(default=100, help_text=b'Bestimmt die Reihenfolge der Elemente. Elemente mit gr\xc3\xb6\xc3\x9feren Zahlen erscheinen weiter unten beziehungsweise hinten.', verbose_name=b'Gewichtung'),
        ),
        migrations.AlterField(
            model_name='realestate',
            name='description',
            field=models.TextField(help_text=b'Abs\xc3\xa4tze sind durch Leerzeilen zu trennen. Die ersten 20 W\xc3\xb6rter sind der Anrisstext auf der Startseite. Dieser ist in nur einem Absatz formatiert.', verbose_name=b'Beschreibung'),
        ),
        migrations.AlterField(
            model_name='realestate',
            name='details',
            field=models.CharField(blank=True, help_text=b'Details mit Kommas trennen, zum Beispiel: Fu\xc3\x9fbodenheizung,Kamin,WG geeignet,Badewanne', max_length=255, verbose_name=b'Details'),
        ),
        migrations.AlterField(
            model_name='realestate',
            name='energy_certificate',
            field=models.CharField(help_text=b'Angaben mit Kommas trennen, zum Beispiel: Verbrauchsausweis,100 kWH/(m\xc2\xb2*a),Erdgas,1980,B', max_length=255, verbose_name=b'Energieausweis'),
        ),
        migrations.AlterField(
            model_name='realestate',
            name='online',
            field=models.BooleanField(default=True, help_text=b'Dieses Feld kann benutzt werden, um eine Wohnung erst sp\xc3\xa4ter freizuschalten.', verbose_name=b'Online'),
        ),
        migrations.AlterField(
            model_name='realestate',
            name='size',
            field=models.PositiveIntegerField(help_text=b'Angabe in m\xc2\xb2', verbose_name=b'Gr\xc3\xb6\xc3\x9fe'),
        ),
        migrations.AlterField(
            model_name='realestate',
            name='when_free',
            field=models.CharField(default=b'sofort', max_length=255, verbose_name=b'Verf\xc3\xbcgbar ab'),
        ),
    ]
